apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0.37-debian
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      ports:
        - containerPort: 3306
