apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod
spec:
  containers:
    - name: app-container
      image: igoryy/fiap-6soat:2
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-configmap
      env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-opaque
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-opaque
                key: DB_PASSWORD