apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-container
          image: igoryy/fiap-6soat:2
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-configmap
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-opaque
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-opaque
                  key: DB_PASSWORD