apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MYSQL_URL: jdbc:mysql://dbsoat.c17nopx11l6k.us-east-1.rds.amazonaws.com:3306/db_soat?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
