apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: rds-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rds-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rds-access-sa
    namespace: default
roleRef:
  kind: Role
  name: rds-access
  apiGroup: rbac.authorization.k8s.io