name: "1 - Build and PR"

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'feature**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: mvn test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test
        run: mvn clean verify

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.projectKey=6SOATGROUP74_shogun-lanches-challenge \
          -Dsonar.organization=shogun-lanches \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.qualitygate.wait=true \
          -Dsonar.sources=src/main \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.branch.name=${GITHUB_REF#refs/heads/} \
          -Dsonar.branch.target=main \
          -Dsonar.exclusions=\
          com/example/demo/core/domain/*,\
          com/example/demo/adapter/controller/CustomExceptionHandlers.class,\
          com/example/demo/adapter/controller/response/**,\
          com/example/demo/adapter/controller/request/**,\
          com/example/demo/config/*,\
          com/example/demo/infrastructure/integration/pagbank/request/*,\
          com/example/demo/infrastructure/integration/pagbank/response/*,\
          com/example/demo/infrastructure/integration/pagbank/presenter/*,\
          com/example/demo/adapter/presenter/**,\
          com/example/demo/exceptions/*,\
          com/example/demo/infrastructure/repository/entity/*,\
          com/example/demo/infrastructure/repository/presenter/*

  create-pr:
    needs: [build, test, sonarcloud]
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create Pull Request to develop
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        base: main
        title: 'PR : Aberto via actions'
        body: 'Bora Brasil !!!.'

