name: Build and Test (Javao)

on:
  push:
    branches: [ feature/** ]
#  pull_request:
#    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Build with Maven
        run: mvn package

      - name: Run tests
        run: mvn test

      - name: Validar diretorio
        run: ls -la

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add changes from CI build
          branch: release
          base: main
          title: 'CI Build - Add changes'
          body: |
            This PR was created automatically by the CI pipeline.
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare JaCoCo Badge
        id: jacoco-prepare
        run: |
          mvn jacoco:prepare-agent

      - name: Test Execution
        run: mvn test

      - name: Genarate JaCoCo Badge
        id: jacoco
        run: |
          mvn jacoco:report

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}  \ 
          -Dsonar.projectKey=6SOATGROUP74_shogun-lanches-challenge -Dsonar.organization=shogun-lanches \
          -Dsonar.host.url=https://sonarcloud.io -Dsonar.qualitygate.wait=true \ 
          -Dsonar.sources=src/main -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.branch.name = ${GITHUB_REF#refs/heads/} \
          -Dsonar.branch.target = main



